[package]
name = "mess-term-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
crossterm = "0.27"
ratatui = { version = "0.25", features = ["all-widgets"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
dirs = "5.0"
